name: Apptainer Build Deploy

on:
  pull_request:
  push:

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build Container
    steps:

      - name: Install Apptainer
        run: |
          echo "Free space"
          df -h
          wget https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb
          sudo apt-get install -y ./apptainer_1.2.4_amd64.deb
      - uses: actions/checkout@v3

      - name: Build Container
        run: |
          apptainer build pypack.sif pypack.def

      - name: Login and Deploy Container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          apptainer push pypack.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
